// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd8lYnEUNDQosWoEWRvscN7g2Kb5PPeYM',
    appId: '1:32968004003:web:fd6da1db8ba1504637ca16',
    messagingSenderId: '32968004003',
    projectId: 'reddit-flutter-51df9',
    authDomain: 'reddit-flutter-51df9.firebaseapp.com',
    storageBucket: 'reddit-flutter-51df9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyJ42accV2Hm-W3tLcZGsfdAAT0BcYq20',
    appId: '1:32968004003:android:84a29d4420f0e92137ca16',
    messagingSenderId: '32968004003',
    projectId: 'reddit-flutter-51df9',
    storageBucket: 'reddit-flutter-51df9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR9w_o50MIWXrjmf7wdXX6V0YsaNqKPVA',
    appId: '1:32968004003:ios:941f383ab2d069f337ca16',
    messagingSenderId: '32968004003',
    projectId: 'reddit-flutter-51df9',
    storageBucket: 'reddit-flutter-51df9.appspot.com',
    androidClientId: '32968004003-v2bcpdu7dl0dh0fnnr7p1j3jgqc6hhfd.apps.googleusercontent.com',
    iosClientId: '32968004003-mfnf4ti034qt3u0lc8nlv96e632ame8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTwitter',
  );
}
